PhilippePitzClairoux/Nova_Gestion

webui/package-lock.json, webui/src/app/app-routing.module.ts, webui/src/app/app.component.html, webui/src/app/app.module.ts
Ne plus toucher aux branches des autres afin d'éviter de commit des atrocités sur Dev. 
On n'approuve pas une PR pour le fun d'approuver. Il faut vérifier le code et **LE TESTER**.
=> Delete duplicated imports and missing commas

webui/package.json, webui/proxy.conf.json
Adding proxy file wich redirect to backend server.
Edited package.json -> npm start command to pass as configuration the proxy file.
now we must use npm start instead of ng serve to start the app.
=> Proxy backend

nova-gestion-backend/src/main/java/nova/gestion/controller/TypeUserController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/UserController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/TypeUserMapper.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/UserMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/TypeUserService.java, nova-gestion-backend/src/main/java/nova/gestion/services/UserService.java, nova-gestion-backend/src/main/resources/mybatis/TypeUserMapper.xml, nova-gestion-backend/src/main/resources/mybatis/UserMapper.xml, nova-gestion-backend/test.http
modification du deleteUser dans service et controller
et modification du createUser (idUser au lieu de id)
=> modification du user

nova-gestion-backend/src/main/java/nova/gestion/controller/GradeController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/TypeUserController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/GradeMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/GradeService.java, nova-gestion-backend/src/main/resources/mybatis/GradeMapper.xml, nova-gestion-backend/test.http
=> getAllGrades 

nova-gestion-backend/src/main/java/nova/gestion/controller/BlankController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/ClientController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/BlankMapper.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/ClientMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/BlankService.java, nova-gestion-backend/src/main/java/nova/gestion/services/ClientService.java, nova-gestion-backend/src/main/resources/mybatis/BlankMapper.xml, nova-gestion-backend/src/main/resources/mybatis/ClientMapper.xml, nova-gestion-backend/test.http
j'ai corrigé le delete de client et blank
=> Correction des deletes

nova-gestion-backend/src/main/java/nova/gestion/services/BlankService.java, nova-gestion-backend/src/main/resources/application.yml
totally didnt accept a pr too quickly
=> Correction gestion blank

nova-gestion-backend/src/main/java/nova/gestion/controller/ProgramController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/ProgramMapper.java, nova-gestion-backend/src/main/java/nova/gestion/model/Program.java, nova-gestion-backend/src/main/java/nova/gestion/services/ProgramService.java, nova-gestion-backend/src/main/resources/mybatis/ProgramMapper.xml, nova-gestion-backend/test.http
j'ai fait un getAllPrograms normal qui ne tient compte de client
=> getProgram et getAllPrograms fonctionnel

nova-gestion-backend/src/main/java/nova/gestion/controller/MachineController.java, webui/src/app/app.module.ts, webui/src/app/inventory/inventory.module.ts, webui/src/app/machines/machine/machine.component.html, webui/src/app/machines/machine/machine.component.scss, webui/src/app/machines/machine/machine.component.ts, webui/src/app/machines/machines-list/machines-list.component.html, webui/src/app/machines/machines-list/machines-list.component.scss, webui/src/app/machines/machines-list/machines-list.component.ts, webui/src/app/machines/machines-routing.module.ts, webui/src/app/machines/machines.module.ts, webui/src/app/models/machine.ts, webui/src/app/models/maintenance.ts, webui/src/app/models/model.ts, webui/src/app/navigation/sidebar/sidebar.component.html, webui/src/app/navigation/sidebar/sidebar.component.scss, webui/src/app/services/machine.service.ts
Ajouter une machine
Modifier une machine
Afficher les machines
Supprimer une machine
=> Gestion des machines

webui/src/app/inventory/blank/blank/blank.component.scss, webui/src/app/machines/machines-list/machines-list.component.ts, webui/src/app/navigation/sidebar/sidebar.component.html, webui/src/app/navigation/sidebar/sidebar.component.scss, webui/src/styles.scss
Toutes les corrections demandées par le client.
Il manque juste les angular material paginator à traduire en français.
=> Correction client 1

database/init.sql, nova-gestion-backend/src/main/java/nova/gestion/controller/ProgramController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/WorkSheetClientProgramMapper.java, nova-gestion-backend/src/main/java/nova/gestion/model/Program.java, nova-gestion-backend/src/main/java/nova/gestion/model/WorkSheetClientProgram.java, nova-gestion-backend/src/main/java/nova/gestion/services/ProgramService.java, nova-gestion-backend/src/main/resources/mybatis/ProgramMapper.xml, nova-gestion-backend/src/main/resources/mybatis/WorkSheetClientProgramMapper.xml, nova-gestion-backend/test.http, webui/src/app/app.module.ts
là j'ai enlevé le client de l'objet Program et j'ai corrigé les erreurs en lien
=> program backend

nova-gestion-backend/src/main/java/nova/gestion/NovaGestion.java, nova-gestion-backend/src/main/java/nova/gestion/controller/StatusController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/StatusMapper.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/WorkSheetMapper.java, nova-gestion-backend/src/main/java/nova/gestion/model/WorkSheet.java, nova-gestion-backend/src/main/java/nova/gestion/model/WorkSheetClientProgram.java, nova-gestion-backend/src/main/java/nova/gestion/services/StatusService.java, nova-gestion-backend/src/main/resources/mybatis/StatusMapper.xml, nova-gestion-backend/src/main/resources/mybatis/WorkSheetMapper.xml, nova-gestion-backend/test.http
=> Status service

nova-gestion-backend/src/main/java/nova/gestion/controller/WorkSheetController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/WorkSheetClientProgramMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/WorkSheetService.java, nova-gestion-backend/src/main/resources/mybatis/WorkSheetClientProgramMapper.xml, nova-gestion-backend/test.http
getWorkSheet et updateWorkSheet fonctionnels
=> correction du getWorkSheet et updateWorkSheet

nova-gestion-backend/src/main/java/nova/gestion/controller/WorkSheetController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/WorkSheetClientProgramMapper.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/WorkSheetMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/WorkSheetService.java, nova-gestion-backend/src/main/resources/mybatis/WorkSheetClientProgramMapper.xml, nova-gestion-backend/src/main/resources/mybatis/WorkSheetMapper.xml, nova-gestion-backend/test.http
le deleteWorkSheet est fonctionnel et ça delete aussi dans la table d'association
=> deleteWorkSheet backend

nova-gestion-backend/src/main/java/nova/gestion/services/BlankService.java, nova-gestion-backend/src/main/resources/mybatis/CoolantHoleMapper.xml
did simple tests ; please test again just to make sure
=> cleaned up code

nova-gestion-backend/src/main/java/nova/gestion/controller/TaskController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/TaskMapper.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/TaskTypeMapper.java, nova-gestion-backend/src/main/java/nova/gestion/model/Task.java, nova-gestion-backend/src/main/java/nova/gestion/services/TaskService.java, nova-gestion-backend/src/main/resources/mybatis/TaskMapper.xml, nova-gestion-backend/src/main/resources/mybatis/TaskTypeMapper.xml
=> Backend taches

nova-gestion-backend/src/main/java/nova/gestion/controller/ProgramController.java, nova-gestion-backend/src/main/java/nova/gestion/model/WorkSheetClientProgram.java, webui/src/app/app.module.ts, webui/src/app/models/program.model.ts, webui/src/app/programs/program/program.component.html, webui/src/app/programs/program/program.component.scss, webui/src/app/programs/program/program.component.ts, webui/src/app/programs/programs-list/programs-list.component.html, webui/src/app/programs/programs-list/programs-list.component.scss, webui/src/app/programs/programs-list/programs-list.component.ts, webui/src/app/programs/programs-routing.module.ts, webui/src/app/programs/programs.module.ts, webui/src/app/services/client.service.ts, webui/src/app/services/program.service.ts, webui/src/app/users/users-list/users-list.component.scss
Afficher tous les programmes et permettre de rechercher parmi ceux-ci.
Afficher un programme en particulier
Ajouter un programme
Modifier un programme
Supprimer un programme
Vérification lors d'un ajout et d'une modification (sur les entrées utilisateurs)
=> Program management

nova-gestion-backend/src/main/resources/mybatis/TaskMapper.xml, nova-gestion-backend/src/main/resources/mybatis/WorkSheetMapper.xml, nova-gestion-backend/test.http
retourne un array de tasks quand on fait getWorkSheet
=> implémenter tasks dans work sheet

nova-gestion-backend/src/main/java/nova/gestion/controller/MaintenanceController.java, nova-gestion-backend/src/main/java/nova/gestion/mappers/MaintenanceMapper.java, nova-gestion-backend/src/main/java/nova/gestion/services/MaintenanceService.java, nova-gestion-backend/src/main/resources/mybatis/MaintenanceMapper.xml, nova-gestion-backend/test.http
gestion des maintenances: add, update, delete
=> Gestion des maintenances - BackEnd

database/insert.sql, nova-gestion-backend/src/main/java/nova/gestion/authentication/CustomAuthenticationProvider.java, nova-gestion-backend/src/main/java/nova/gestion/errors/controller/CustomGlobalExceptionHandler.java, nova-gestion-backend/src/main/java/nova/gestion/errors/model/Error.java
Fixed a few bugs, updated salts in database for the new version of BCrypt and updated the error message formats for now. Will update them later
=> Auth quick fix

webui/src/app/services/users.service.ts
This pr is to fix a bug in user.service
=> OOGA BOOGA

nova-gestion-backend/src/main/java/nova/gestion/controller/BlankController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/ClientController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/GradeController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/MachineController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/MaintenanceController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/ProgramController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/StatusController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/TaskController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/TaskTypeController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/ToolController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/TypeCoolantHoleController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/TypeUserController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/UserController.java, nova-gestion-backend/src/main/java/nova/gestion/controller/WorkSheetController.java
j'ai ajouté un peu de documentation dans les controller
=> doccumentation dans les controllers

database/init.sql, nova-gestion-backend/src/main/java/nova/gestion/model/Program.java, nova-gestion-backend/src/main/resources/mybatis/ProgramMapper.xml, nova-gestion-backend/test.http
donc à la création il est activé par défaut
à la suppression activated=0
=> ajout de activated pour program

nova-gestion-backend/src/main/java/nova/gestion/authentication/CustomAuthenticationProvider.java, nova-gestion-backend/src/main/resources/mybatis/BlankMapper.xml, nova-gestion-backend/src/main/resources/mybatis/ToolMapper.xml, webui/src/app/Guard/auth.guard.ts, webui/src/app/app-routing.module.ts, webui/src/app/app.module.ts, webui/src/app/authentification/authentification/authentification.component.ts, webui/src/app/clients/clients-list/clients-list.component.html, webui/src/app/clients/clients-list/clients-list.component.scss, webui/src/app/clients/clients-routing.module.ts, webui/src/app/inventory/blank/blanks-list/blanks-list.component.ts, webui/src/app/inventory/inventory-routing.module.ts, webui/src/app/inventory/tools/tools-list/tools-list.component.ts, webui/src/app/machines/machine/machine.component.html, webui/src/app/machines/machine/machine.component.scss, webui/src/app/machines/machines-list/machines-list.component.ts, webui/src/app/machines/machines-routing.module.ts, webui/src/app/navigation/sidebar/sidebar.component.html, webui/src/app/navigation/sidebar/sidebar.component.scss, webui/src/app/navigation/sidebar/sidebar.component.ts, webui/src/app/programs/program/program.component.html, webui/src/app/programs/programs-routing.module.ts, webui/src/app/services/authentification.service.ts, webui/src/app/users/user/user.component.ts, webui/src/app/users/users-routing.module.ts, webui/src/app/worksheets/worksheets-routing.module.ts
Added personalized menu depending on user
Added authentification guard redirecting upon not behing logged in
added verification on password upon creating new user
added some error handling for login
fixed issue in login backend
fixed few visual issues
fixed user password issues on update
fixed routing problems
=> Authentification fixed

nova-gestion-backend/src/main/java/nova/gestion/services/BlankService.java, nova-gestion-backend/src/main/java/nova/gestion/services/ProgramService.java, nova-gestion-backend/src/main/java/nova/gestion/services/ToolService.java, nova-gestion-backend/src/main/resources/mybatis/ProgramMapper.xml, nova-gestion-backend/src/main/resources/mybatis/ToolMapper.xml, nova-gestion-backend/test.http
- programme -> tige/outil peut etre null (update) : le update est fonctionnel quand outil ou tige est null
- emballeur a acces a getAllPrograms
- Update tool fonctionnel
=> Correction bug backend

database/init.sql, database/insert.sql, nova-gestion-backend/src/main/java/nova/gestion/model/Blank.java, nova-gestion-backend/src/main/java/nova/gestion/services/BlankService.java, nova-gestion-backend/src/main/resources/mybatis/BlankMapper.xml, nova-gestion-backend/test.http
l'ajout et le update sont fonctionnels avec ce nouvel ajout
=> Ajout de code dans la class blank et la table blank

database/init.sql, nova-gestion-backend/src/main/resources/mybatis/BlankMapper.xml, nova-gestion-backend/src/main/resources/mybatis/ClientMapper.xml, nova-gestion-backend/src/main/resources/mybatis/MachineMapper.xml, nova-gestion-backend/src/main/resources/mybatis/ToolMapper.xml, nova-gestion-backend/src/main/resources/mybatis/UserMapper.xml, nova-gestion-backend/src/main/resources/mybatis/WorkSheetMapper.xml
entries are now disabled instead of being deleted
=> entries are now disabled instead of deleted!

database/init.sql, nova-gestion-backend/src/main/java/nova/gestion/controller/TaskController.java, nova-gestion-backend/src/main/java/nova/gestion/model/Task.java, nova-gestion-backend/src/main/java/nova/gestion/services/TaskService.java, nova-gestion-backend/src/main/resources/mybatis/TaskMapper.xml, webui/src/app/models/task.ts, webui/src/app/worksheets/tasks/tasks.component.html
=> Task management quickfix

webui/package-lock.json, webui/package.json, webui/src/app/app-routing.module.ts, webui/src/app/app.module.ts, webui/src/app/inventory/inventory.module.ts, webui/src/app/models/order-history.ts, webui/src/app/navigation/sidebar/sidebar.component.html, webui/src/app/rapports/rapport-blanks/rapport-blanks.component.html, webui/src/app/rapports/rapport-blanks/rapport-blanks.component.scss, webui/src/app/rapports/rapport-blanks/rapport-blanks.component.ts, webui/src/app/rapports/rapport-tasks/rapport-tasks.component.html, webui/src/app/rapports/rapport-tasks/rapport-tasks.component.ts, webui/src/app/rapports/rapports-routing.module.ts, webui/src/app/rapports/rapports.module.ts, webui/src/app/rapports/rapports/rapports.component.html, webui/src/app/rapports/rapports/rapports.component.scss, webui/src/app/rapports/rapports/rapports.component.ts, webui/src/app/services/blank.service.ts, webui/src/app/shared/pipes/truncate.pipe.ts, webui/src/app/shared/shared.module.ts, webui/src/app/worksheets/worksheet/worksheet.component.ts
=> Rapport blanks

nova-gestion-backend/src/main/java/ca/nova/gestion/services/ProgramService.java
=> removed bad import
